//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarnHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public bool Status { get; set; }
        public int PostId { get; set; }
        public int UserId { get; set; }
        public int ExecuterId { get; set; }
        public Nullable<int> CategorId { get; set; }
        public int Date { get; set; }
        public string Desc { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
